#title in header
title: "Wintersweet."

#main info
#owner
owner: "Mei Jiaojiao"
email: wintersweetjiaojiao@outlook.com
info: "Where my heart lies, let my brain lies also.ğŸ˜"
#description
desc: "Currently I am a master's student majoring in Artificial Intelligence, with fully-founded support of Chinese government scholarships  ğŸ‡¨ğŸ‡³ and  Stipendium Hungaricum scholarship programme ğŸ‡­ğŸ‡º . Bachelor's studies in Electronic Engineering, with two papers in signal processing, prizes in mathematical modeling competitions, two exchange semester programs, a degree in Chinese Law, eight months experience in patents drafting and analysis. This site is created to record my studying notes.ğŸ“’"

#menu
menu:
  Works: /works
  About: /about

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Budapest,Hungary
placelink: https://en.wikipedia.org/wiki/Budapest
github: https://github.com/JIAOJIAOMEI
linkedin: https://www.linkedin.com/in/mei-jiaojiao-b4701b246/
# twitter: https://twitter.com/adisaktijrs
instagram: https://www.instagram.com/wintersweet991217/
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
